language: cpp

branches:
  only:
    - master

matrix:
  include:

    # disabled as too expensive
    # - name: "AppleWin on Windows"
    #   os: windows
    #   script: ./CIBuild.bat

    - name: "AppleWin on Linux"
      os: linux
      dist: focal
      arch: amd64

      script: source/linux/build.sh

      addons:
        apt:
          packages:
            - cmake
            - libyaml-dev
            - libminizip-dev
            - qtbase5-dev
            - qtmultimedia5-dev
            - libqt5gamepad5-dev
            - libncurses-dev
            - libevdev-dev
            - libsdl2-dev
            - libsdl2-image-dev
            - libgles-dev
            - libpcap-dev
            - libslirp-dev
